### ISSUE TITLE
Support setting custom fields?

### ISSUE THREAD

**Issue by psyked** [atlassian/gajira-create#2]
It would be really nice to be able to set custom fields on a ticket when creating them. At the moment I'm having to do a two-step workaround using the following code snippet:

``` yaml
           - name: Set JIRA Ticket Epic
              run: >
                  curl 
                  -u ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}
                  -X PUT 
                  -H 'Content-Type: application/json'
                  -d '{"fields":{"customfield_10008":"MEER-105"}}'
                  ${{ secrets.JIRA_BASE_URL }}/rest/api/2/issue/${{ steps.create.outputs.issue }}
```

**Comment by DanielHilton** [comment]
I would add to this, that if a JIRA project is configured to use a custom field that is mandatory for issue creation, it means this tool as it is right now cannot be used as the issue creation fails.

**Comment by rudzon** [comment]
Hi, 

Added custom field support for in new release ( https://github.com/atlassian/gajira-create/releases/tag/v2.0.1 )

can be used as: 
```
with:
        project: GA
        issuetype: Build
        summary: |
          Build completed for ${{ github.repository }}
        description: |
          Compare branch|${{ github.event.compare }} # https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads
        fields: '{"customfield_10171": "field value from actions"}'
```
