### ISSUE TITLE
Assignee?

### ISSUE THREAD

**Issue by rafi-fisker** [atlassian/gajira-create#25]
How can we assign to a user?

I tried 
```
    - name: Create
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: ABCD
        issuetype: Task
        summary: |
          Test issue
        description: |
          This is a test
        fields: '{"assignee": "<accountId>"}'
```
Not having any luck. I tried account ID and email.
It creates the ticket Unassigned. If I don't set that field it creates with the default assignee.
