### ISSUE TITLE
Drop down custom fields are not working on Jira Cloud

### ISSUE THREAD

**Issue by via-justa** [atlassian/gajira-create#33]
Drop down custom fields are not working on Jira Cloud

job configuration
```yaml
    - name: Create
      id: create
      uses: atlassian/gajira-create@master
      if: env.CREATE_ISSUE == 'true'
      with:
        project: XXXX
        issuetype: Task
        summary: "[PR Created] ${{ github.event.pull_request.title }}"
        description: |
          **Created by:** ${{ github.actor }}
          **PR:** https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}
          **Description:** 
          ${{ github.event.pull_request.body }}
        fields: '{"customfield_10148": "DevOps", "customfield_10151": "Change request" , "customfield_10154": "True"}'
```

Field configuration for `customfield_10154` as an example
```json
"customfield_10154": {
    "required": false,
    "schema": {
        "type": "option",
        "custom": "com.atlassian.jira.plugin.system.customfieldtypes:select",
        "customId": 10154
    },
    "name": "Auto Created Issue",
    "key": "customfield_10154",
    "hasDefaultValue": true,
    "operations": [
        "set"
    ],
    "allowedValues": [
        {
            "self": "https://up42.atlassian.net/rest/api/2/customFieldOption/10232",
            "value": "False",
            "id": "10232"
        },
        {
            "self": "https://up42.atlassian.net/rest/api/2/customFieldOption/10233",
            "value": "True",
            "id": "10233"
        }
    ],
    "defaultValue": {
        "self": "https://up42.atlassian.net/rest/api/2/customFieldOption/10232",
        "value": "False",
        "id": "10232"
    }
},
```

Job error
```
originError: Error: Bad Request
       at /home/runner/work/_actions/atlassian/gajira-create/master/dist/index.js:1:57112
       at processTicksAndRejections (internal/process/task_queues.js:97:5)
       at async Jira.fetch (/home/runner/work/_actions/atlassian/gajira-create/master/dist/index.js:1:63273)
       at async e.exports.execute (/home/runner/work/_actions/atlassian/gajira-create/master/dist/index.js:1:186085)
       at async exec (/home/runner/work/_actions/atlassian/gajira-create/master/dist/index.js:1:7099),
   source: 'jira',
   jiraError: {
     customfield_10148: "Specify a valid 'id' or 'name' for Domain",
     customfield_10151: "Specify a valid 'id' or 'name' for Change type",
     customfield_10154: "Specify a valid 'id' or 'name' for Auto Created Issue"
   }
 }

```
