### ISSUE TITLE
Markdown not evaluated correctly

### ISSUE THREAD

**Issue by via-justa** [atlassian/gajira-create#34]
We're sending the PR description as the body of the `description` and Jira does not evaluate it correctly.
In the example you can see we send `> ` for quote and ``'`'`` to create "coded" text. We also tried sending `###` for heading but it got evaluated as nested list.
```
Created by: "<actor name>"
PR: https://github.com/<org>/<repo>/pull/<pr number>
Description: 
Pull Request
============
>  Tracked in JIRA 

*Scope of the PR*

Add GitHub workflow to auto create Jira issue in `SRE Requests` in the following conditions:

No XXXX issue is mentioned in the subject or description when the PR is created

The user is not part of the SRE Team 

This workflow is using the following Org level secrets:

`AUTO_JIRA_ISSUE_FROM_PR` for GitHub API requests

`JIRA_USER_EMAIL` and `JIRA_API_TOKEN` for Jira API requests 
```
How can we instruct Jira to evaluate the body as markdown?

Action code
```yaml
- name: Create
      id: create
      uses: atlassian/gajira-create@master
      if: env.CREATE_ISSUE == 'true'
      with:
        project: <project ID>
        issuetype: Task
        summary: "[PR Created] ${{ github.event.pull_request.title }}"
        description: |
          *Created by:* ${{ needs.get_actor_teams.outputs.name }}
          *PR:* https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}
          *Description:* 
          ${{ github.event.pull_request.body }}
```
