### ISSUE TITLE
Support for Atlassian Format Document

### ISSUE THREAD

**Issue by francosang** [atlassian/gajira-create#35]
One of our requirements for our CI setup is to create a Jira ticket as part of the job with a specific formatted rich text in the ticket's description.

Currently, we archive this using the [v3 API for creating issues](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-post) and the [Atlassian Format Document](https://developer.atlassian.com/cloud/jira/platform/apis/document/structure/) in the `description` property. 

We have been trying to get the same result with the `gajira-create` but without any luck.

I have tried different action configurations, with multiline and single-line texts, single quotes and double quotes, escaping characters, and more combinations. 
But the resulting Jira ticket description is always a plain JSON text.

```yaml
      - name: Create Jira task
        id: create-jira-task
        uses: atlassian/gajira-create@v2.0.1
        with:
          project: PROJ
          issuetype: Task
          fields: '{"priority": {"name": "Highest"}}'
          summary: TITLE
          description: "{ \"version\":1, \"type\":\"doc\", \"content\":[{\"type\":\"heading\",\"attrs\":{\"level\":1},\"content\":[{\"type\":\"text\", \"text\":\"Header\"}]}]}"
#         description: '{ "version":1, "type":"doc", "content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text", "text":"Changelog"}]}]}'
```
I have not found any examples or alternatives on the web.
Is it possible to do this?
