### ISSUE TITLE
Labels aren't applied successfully on created issues

### ISSUE THREAD

**Issue by jesseadams** [atlassian/gajira-create#54]
In this example:

```
      - name: Create JIRA Issue
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: IL23
          issuetype: Task
          summary: CI Failure for ${{ github.repository }}
          description: Please see full details at https://github.com/${{ github.repository}}/actions/runs/${{ github.run_id }}
          fields: '{"labels": ["ExampleLabel"]}'
```

It creates the Task in JIRA for the correct project, but the label doesn't exist.

**Comment by joshkay10** [comment]
Hi Jesse, 
My team recently took over some of these actions, I went through the process from scratch and I am getting labels appear using the same syntax as you... 

Would you be able to retry?

Unlikely, but can you double check that the actions were successful in your GitHub actions tab, just incase it returned an error.


```
    - name: Create
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: E2E
        issuetype: Task
        summary: Test task from GH
        description: details of things
        fields: '{"labels": ["ExampleLabel"]}'
        
        # Show me the new issue
    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
        
```
        
<img width="390" alt="Screenshot 2023-09-19 at 2 25 21 PM" src="https://github.com/atlassian/gajira-create/assets/3848691/a678bf7f-408a-4f22-9616-9566ec7189da">
<img width="278" alt="Screenshot 2023-09-19 at 2 25 10 PM" src="https://github.com/atlassian/gajira-create/assets/3848691/cc879f7d-21bb-4a01-966b-fb03ef92e33a">
